apiVersion: v1
kind: Service
metadata:
  name: tfg-uoc-app
  namespace: devel
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    run: tfg-uoc-app
  type: NodePort